include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types: true
    - avoid_print: true
    - prefer_single_quotes: true
    - require_trailing_commas: true
    - prefer_final_locals: true
    - avoid_relative_lib_imports: true
    - constant_identifier_names: true
    - directives_ordering: true
    - package_api_docs: true
    - test_types_in_equals: true
    - throw_in_finally: true
    - unnecessary_statements: true
